.TH ECIG 6
.SH NAME
ecig \- A cigarette simulator for your Linux terminal.

.SH DESCRIPTION
Ecig uses the ncurses library. Has auto smoking features so that you can smoke in the background and a ranking system based on your level of addiction

.SH KEYBINDS
L: Light
.br
D: Take a Drag (hold)
.br
F: Flick ashes
.br
S: Stub out
.br
C: Chain smoke (auto light)
.br
A: Auto drag
.br
X: Auto flick

.SH FILES
/usr/bin/ecig
.br
	The executable.
.br
/usr/share/man/man6/ecig.6.bz2
.br
	The ecig man page.
.br
~/.cigs
.br
	Stored total number of cigs you have smoked.

.SH SEE ALSO
ncurses(3X)

.SH AUTHOR
Ecig was created by Nikolai Klover who goes by the alias of Cat Peep online.
